eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.1.204:8761/eureka/

server:
  port: 8769

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000